INSERT INTO TB_STATUSCHAMADO(DS_STATUS,TG_INATIVO,DH_INCLUSAO)
VALUES('PENDENTE',0 ,NOW());
INSERT INTO TB_STATUSCHAMADO(DS_STATUS,TG_INATIVO,DH_INCLUSAO)
VALUES('EM ATENDIMENTO',0 ,NOW());
INSERT INTO TB_STATUSCHAMADO(DS_STATUS,TG_INATIVO,DH_INCLUSAO)
VALUES('FINALIZADO',0 ,NOW());
INSERT INTO TB_STATUSCHAMADO(DS_STATUS,TG_INATIVO,DH_INCLUSAO)
VALUES('CANCELADO',0 ,NOW());

INSERT INTO TS_LOGIN(ds_login, ds_senha, TG_INATIVO, DH_INCLUSAO)
VALUES('Darlan.Silva','$2a$12$xBZxLQSFupxAbUrRJwFOv.2JxU6edK/JsRn/qgv677Lww1xRROa5G', 0, now());
INSERT INTO TS_PERMISSAOACESSO(PERMISSAO, DH_INCLUSAO, TG_INATIVO)
VALUES("ROLE_ADMIN",NOW(),0);
INSERT INTO TS_LOGIN_PERMISSAOACESSO(LOGIN_PK_ID,	PERMISSAO_ACESSO_PK_ID)
VALUES(1,1);
